# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "{ bjorge.xyz }"
email: contact@bjorge.xyz
description: > # this means to ignore newlines until "baseurl:"
    Ingénieur logiciels de 25 ans, j'ai pas toujours des trucs à dire mais je les dis quand même.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.bjorge.xyz" # the base hostname & protocol for your site
twitter_username: bj0rge
github_username:  bj0rge
disqus_shortname: bjorge-xyz
subtitle-quote: Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live.
subtitle-author: John F. Woods
sass:
    sass_dir: _sass

# Build settings
markdown: kramdown

exclude: ["node_modules", "gulpfile.js", "package.json"]

